[package]
name = "euler"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
color-eyre = "0.6.3"
paste = "1.0.15"
regex = "1.11.1"
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls"] }
scraper = "0.22.0"
tokio = { version = "1.43.0", default-features = false, features = ["macros", "rt-multi-thread"] }
